{
    "name": "OpenSPP Attendance: DSWD",
    "category": "OpenSPP",
    "version": "17.0.1.0.0",
    "sequence": 1,
    "author": "OpenSPP.org",
    "website": "https://github.com/OpenSPP/openspp-modules",
    "license": "LGPL-3",
    "development_status": "Alpha",
    "maintainers": ["reichie020212"],
    "depends": ["spp_attendance"],
    "data": [
        "data/attendance_type_data.xml",
        "data/ir_config_parameter_data.xml",
    ],
    "assets": {},
    "demo": [],
    "images": [],
    "application": True,
    "installable": True,
    "auto_install": False,
}
