# Do NOT update manually; changes here will be overwritten by Copier
_commit: fdfbd3c
_src_path: https://github.com/openspp-project/openspp-odoo-addons-repo-template.git
ci: GitHub
dependency_installation_mode: OCA
generate_requirements_txt: true
github_check_license: true
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_version: 15.0
org_name: OpenSPP.org
org_slug: openspp-project
rebel_module_groups: []
repo_description: Programs and cycles are used to outline a social protection program.
    This is an OpenSPP feature that is extremely flexible and expandable to manage
    different type of programs and cycles.
repo_name: OpenSPP Program
repo_slug: openspp-program
repo_website: https://github.com/openspp-project/openspp-program
travis_apt_packages: []
travis_apt_sources: []

