{
    "name": "OpenSPP OpenID VCI Individual",
    "category": "OpenSPP",
    "version": "17.0.1.3.0",
    "sequence": 1,
    "author": "OpenSPP.org",
    "website": "https://github.com/OpenSPP/openspp-modules",
    "license": "LGPL-3",
    "development_status": "Production/Stable",
    "maintainers": ["jeremi", "gonzalesedwin1123"],
    "depends": ["spp_openid_vci", "g2p_registry_individual"],
    "external_dependencies": {"python": ["qrcode"]},
    "data": ["views/individual_view.xml"],
    "assets": {},
    "demo": [],
    "images": [],
    "application": True,
    "installable": True,
    "auto_install": False,
    # odoo-upgrades
    "summary": "The spp_openid_vci_individual module extends OpenSPP's Verifiable Credential issuance to individual registrants, enabling secure digital identity and attribute proofs using OpenID4VP and DIDs. It integrates VC issuance directly into individual profiles, supporting verifiable presentations and customizable issuer configurations for program-specific data.",
}
