# Part of OpenSPP. See LICENSE file for full copyright and licensing details.
{
    "name": "G2P Connect Demo",
    "category": "OpenSPP",
    "version": "17.0.1.3.0",
    "sequence": 1,
    "author": "OpenSPP.org",
    "website": "https://github.com/OpenSPP/openspp-modules",
    "license": "LGPL-3",
    "development_status": "Beta",
    "maintainers": ["jeremi", "gonzalesedwin1123", "reichie020212"],
    "depends": [
        "spp_base_demo",
        "g2p_registry_base",
        "g2p_registry_individual",
        "g2p_registry_group",
        "g2p_registry_membership",
        "g2p_programs",
        "spp_custom_field",
        "spp_entitlement_cash",
        "spp_idpass",
        "spp_idqueue",
        "spp_area",
        "spp_event_data",
        "spp_service_points",
        "theme_openspp_muk",
        "queue_job",
        "spp_custom_filter",
        "product",
        "stock",
    ],
    "external_dependencies": {"python": ["faker"]},
    "data": [
        "security/ir.model.access.csv",
        "data/sample_data.xml",
        "views/generate_data_view.xml",
        "views/groups_view.xml",
        "views/individuals_view.xml",
    ],
    "assets": {},
    "demo": [],
    "images": [],
    "application": True,
    "installable": True,
    "auto_install": False,
}
