# Do NOT update manually; changes here will be overwritten by Copier
_commit: 79935fe
_src_path: https://github.com/openspp/openspp-odoo-addons-repo-template.git
ci: GitHub
dependency_installation_mode: OCA
generate_requirements_txt: true
github_check_license: false
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
odoo_version: 15.0
org_name: OpenSPP.org
org_slug: openspp
rebel_module_groups: []
repo_description: OpenSPP Demo Repo
repo_name: OpenSPP Demo
repo_slug: openspp-demo
repo_website: https://github.com/openspp/openspp-demo
travis_apt_packages: []
travis_apt_sources: []

