{
    "name": "OpenSPP Change Request: Add Group to a Group",
    "summary": "Facilitates change requests to add individual farmers to an existing group with membership validation and document tracking.",
    "category": "OpenSPP",
    "version": "17.0.1.3.1",
    "sequence": 1,
    "author": "OpenSPP.org",
    "website": "https://github.com/OpenSPP/openspp-modules",
    "license": "LGPL-3",
    "development_status": "Production/Stable",
    "maintainers": ["jeremi", "gonzalesedwin1123"],
    "depends": [
        "spp_change_request",
        "g2p_registry_individual",
        "g2p_registry_group",
        "g2p_registry_membership",
        "spp_registry_group_hierarchy",
    ],
    "excludes": [],
    "data": [
        "security/change_request_security.xml",
        "security/ir.model.access.csv",
        "data/dms.xml",
        "data/change_request_stage.xml",
        "data/change_request_sequence.xml",
        "data/change_request_target.xml",
        "views/change_request_add_group_to_group_view.xml",
        "views/change_request_view.xml",
        "views/dms_file_view.xml",
    ],
    "assets": {},
    "demo": [],
    "images": [],
    "application": False,
    "installable": True,
    "auto_install": False,
}
