{
    "name": "OpenSPP User Roles",
    "category": "OpenSPP",
    "version": "17.0.1.3.1",
    "sequence": 1,
    "author": "OpenSPP.org",
    "website": "https://github.com/OpenSPP/openspp-modules",
    "license": "LGPL-3",
    "development_status": "Production/Stable",
    "maintainers": ["jeremi", "gonzalesedwin1123"],
    "depends": [
        "base",
        "mail",
        "g2p_registry_base",
        "g2p_registry_group",
        "spp_area",
        "spp_idqueue",
        "base_user_role",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/local_roles.xml",
        "data/global_roles.xml",
        "data/ir_cron.xml",
        "views/role.xml",
        "views/user.xml",
    ],
    "assets": {},
    "demo": [],
    "images": [],
    "application": True,
    "installable": True,
    "auto_install": False,
    "summary": "The OpenSPP User Roles module defines and manages distinct user roles, categorizing them as global or local, to implement area-based access control. It restricts user access to specific geographical areas by leveraging the spp_area module and automates underlying system permission assignments.",
}
