# Part of OpenSPP. See LICENSE file for full copyright and licensing details.


{
    "name": "OpenSPP Farmer Registry Base",
    "summary": "Base module for managing farmer registries, linking farmers to farms, land, and agricultural activities.",
    "category": "OpenSPP",
    "version": "17.0.1.3.0",
    "sequence": 1,
    "author": "OpenSPP.org",
    "website": "https://github.com/OpenSPP/openspp-modules",
    "license": "LGPL-3",
    "development_status": "Production/Stable",
    "maintainers": ["jeremi", "gonzalesedwin1123", "reichie020212"],
    "depends": [
        "base",
        "base_import",
        "spp_area",
        "spp_area_gis",
        "spp_base_common",
        "spp_base_gis",
        "spp_custom_field",
        "spp_custom_fields_ui",
        "spp_custom_filter_registry_ui",
        "spp_hide_menus",
        "spp_irrigation",
        "spp_land_record",
        "spp_openid_vci_individual",
        "g2p_registry_base",
        "g2p_registry_individual",
        "g2p_registry_group",
        "g2p_registry_membership",
    ],
    "excludes": [
        "spp_base_spmis",
    ],
    "external_dependencies": {"python": ["shapely", "geojson", "simplejson", "pyproj"]},
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/farm_season_view.xml",
        "data/kind_data.xml",
        "data/id_data.xml",
        "views/res_partner.xml",
        "views/configuration_view.xml",
        "views/res_users.xml",
        "views/group_view.xml",
        "views/individual_view.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "spp_base_farmer_registry/static/src/import_records/import_records.js",
        ],
    },
    "demo": [],
    "images": [],
    "application": True,
    "installable": True,
    "auto_install": False,
}
