# Part of OpenSPP. See LICENSE file for full copyright and licensing details.
{
    "name": "OpenSPP Code Generator",
    "category": "OpenSPP",
    "version": "17.0.1.3.1",
    "summary": "This module generates codes for program registrants and groups based on specifications written in a YAML file.",
    "sequence": 1,
    "author": "OpenSPP.org",
    "website": "https://github.com/OpenSPP/openspp-modules",
    "license": "LGPL-3",
    "development_status": "Alpha",
    "maintainers": ["jeremi", "gonzalesedwin1123"],
    "depends": [
        "base",
        "mail",
        "g2p_registry_base",
        "g2p_registry_individual",
        "g2p_registry_group",
        "g2p_registry_membership",
        "g2p_programs",
        "spp_custom_field",
        "spp_custom_fields_ui",
        "spp_cel_domain",
    ],
    "external_dependencies": {
        "python": ["PyYAML"],
    },
    "data": [
        "security/ir.model.access.csv",
        "views/code_generator_views.xml",
    ],
    "assets": {},
    "demo": [],
    "images": [],
    "application": False,
    "installable": True,
    "auto_install": False,
}
