# Part of OpenSPP. See LICENSE file for full copyright and licensing details.
STATE_DRAFT = "draft"
STATE_TO_APPROVE = "to_approve"
STATE_APPROVED = "approved"
STATE_DISTRIBUTED = "distributed"
# STATE_ACTIVE = "active"
STATE_ENDED = "ended"
STATE_CANCELLED = "cancelled"

MANAGER_ELIGIBILITY = 1
MANAGER_CYCLE = 2
MANAGER_PROGRAM = 3
MANAGER_ENTITLEMENT = 4
MANAGER_DEDUPLICATION = 5
MANAGER_NOTIFICATION = 6
MANAGER_PAYMENT = 7
