{
    "name": "OpenSPP SQL Query Eligibility Manager",
    "category": "OpenSPP",
    "version": "17.0.1.0.0",
    "sequence": 1,
    "author": "OpenSPP.org",
    "website": "https://github.com/OpenSPP/openspp-modules",
    "license": "LGPL-3",
    "development_status": "Alpha",
    "maintainers": ["jeremi", "gonzalesedwin1123"],
    "depends": ["base", "g2p_registry_base", "g2p_programs", "spp_programs"],
    "data": ["security/ir.model.access.csv", "wizard/create_program_wizard.xml", "views/eligibility_manager_view.xml"],
    "assets": {},
    "demo": [],
    "images": [],
    "application": True,
    "installable": True,
    "auto_install": False,
    "summary": "Define complex program eligibility criteria using SQL queries for flexible and automated beneficiary enrollment within OpenSPP.",
}
