# Part of OpenSPP. See LICENSE file for full copyright and licensing details.
{
    "name": "OpenSPP In-Kind Entitlement",
    "category": "OpenSPP",
    "version": "17.0.1.3.1",
    "sequence": 1,
    "author": "OpenSPP.org",
    "website": "https://github.com/OpenSPP/openspp-modules",
    "license": "LGPL-3",
    "development_status": "Production/Stable",
    "maintainers": ["jeremi", "gonzalesedwin1123"],
    "depends": [
        "base",
        "g2p_registry_base",
        "g2p_programs",
        "spp_programs",
        "product",
        "stock",
        "spp_service_points",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/entitlement_manager_view.xml",
        "wizard/create_program_wizard.xml",
    ],
    "assets": {},
    "demo": [],
    "images": [],
    "application": True,
    "installable": True,
    "auto_install": False,
    "summary": "This module manages the distribution of non-cash benefits within social protection programs, defining in-kind entitlements and automating their generation for eligible beneficiaries. It integrates with inventory management to track stock and facilitates redemption of goods through designated service points, supporting structured distribution workflows.",
}
