{
    "name": "OpenSPP Custom Filter",
    "category": "OpenSPP",
    "version": "17.0.1.3.1",
    "summary": "The module empowers administrators to precisely control which fields appear in Odoo's filtering interface. This capability streamlines data searches, reduces UI clutter, and enhances the user experience by ensuring only relevant fields are available for filtering.",
    "author": "OpenSPP.org",
    "development_status": "Production/Stable",
    "maintainers": ["nhatnm0612"],
    "website": "https://github.com/OpenSPP/openspp-modules",
    "license": "LGPL-3",
    "depends": ["base"],
    "data": ["views/ir_model_fields_views.xml"],
    "auto_install": False,
    "application": False,
}
