{
    "name": "SPP Audit Log",
    "summary": "Provides audit logging functionality to track data changes and user actions within OpenSPP, enhancing transparency and accountability.",
    "category": "OpenSPP",
    "version": "17.0.1.0.0",
    "sequence": 1,
    "author": "OpenSPP.org",
    "website": "https://github.com/OpenSPP/openspp-modules",
    "license": "LGPL-3",
    "development_status": "Production/Stable",
    "maintainers": ["jeremi", "gonzalesedwin1123", "reichie020212"],
    "depends": ["base", "mail", "g2p_registry_membership"],
    "external_dependencies": {},
    "data": [
        "security/audit_log_security.xml",
        "security/ir.model.access.csv",
        "views/spp_audit_rule_views.xml",
        "views/spp_audit_log_views.xml",
    ],
    "assets": {},
    "demo": [],
    "images": [],
    "application": True,
    "installable": True,
    "auto_install": False,
}
