{
    "name": "OpenSPP: DSWD 4PS",
    "category": "OpenSPP",
    "version": "17.0.1.0.0",
    "sequence": 1,
    "author": "OpenSPP.org",
    "website": "https://github.com/OpenSPP/openspp-modules",
    "license": "LGPL-3",
    "development_status": "Alpha",
    "maintainers": ["reichie020212"],
    "depends": [
        "g2p_registry_base",
        "g2p_registry_group",
        "g2p_registry_individual",
        "g2p_registry_membership",
        "spp_area",
        "spp_programs",
        "spp_cycle_attendance_compliance",
        "spp_ethnic_group",
        "spp_dci_api_server",
        "theme_openspp_muk",
    ],
    "data": [
        "data/res_company_data.xml",
        "data/ethnic_group_data.xml",
        "views/area.xml",
        "views/groups_view.xml",
        "views/individual_view.xml",
        "views/hide_menu_view.xml",
    ],
    "assets": {},
    "demo": [],
    "images": [],
    "application": True,
    "installable": True,
    "auto_install": False,
}
