name: Sync Issue to Odoo

on:
  issues:
    types: [opened, edited]

jobs:
  sync_to_odoo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Sync Issue to Odoo
      env:
        ODOO_URL: ${{ secrets.ODOO_URL }}
        ODOO_DB: ${{ secrets.ODOO_DB }}
        ODOO_USERNAME: ${{ secrets.ODOO_USERNAME }}
        ODOO_PASSWORD: ${{ secrets.ODOO_PASSWORD }}
        TITLE: ${{ github.event.issue.title }}
        BODY: ${{ github.event.issue.body }}
        ISSUE: ${{ github.event.issue.number }}
      run: |
        python scripts/sync_issue_to_odoo.py
