# Part of OpenSPP. See LICENSE file for full copyright and licensing details.
{
    "name": "OpenSPP Manual Entitlement",
    "category": "OpenSPP",
    "version": "17.0.1.3.0",
    "sequence": 1,
    "author": "OpenSPP.org",
    "website": "https://github.com/OpenSPP/openspp-modules",
    "license": "LGPL-3",
    "development_status": "Production/Stable",
    "maintainers": ["jeremi", "gonzalesedwin1123"],
    "depends": [
        "base",
        "g2p_registry_base",
        "g2p_programs",
        "spp_registrant_import",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/cycle_view.xml",
        "wizard/manual_entitlement_wizard.xml",
    ],
    "assets": {},
    "demo": [],
    "images": [],
    "application": True,
    "installable": True,
    "auto_install": False,
    "summary": "Administrators directly create entitlements for beneficiaries within specific program cycles, accommodating exceptional eligibility criteria not covered by automated rules. A step-by-step wizard guides entitlement creation, preventing duplicates for beneficiaries within a program cycle and supporting scalable asynchronous processing.",
}
