{
    "name": "OpenSPP OpenID VCI",
    "category": "OpenSPP",
    "version": "17.0.1.3.1",
    "sequence": 1,
    "author": "OpenSPP.org",
    "website": "https://github.com/OpenSPP/openspp-modules",
    "license": "LGPL-3",
    "development_status": "Production/Stable",
    "maintainers": ["jeremi", "gonzalesedwin1 123"],
    "depends": [
        "spp_encryption",
        "g2p_encryption_rest_api",
        "g2p_registry_base",
        "g2p_openid_vci",
        "g2p_openid_vci_rest_api",
        "spp_user_roles",
    ],
    "external_dependencies": {"python": ["qrcode"]},
    "data": [
        "security/security_access.xml",
        "security/security_user_roles.xml",
        "security/ir.model.access.csv",
        "wizard/vci_issuer_selection_view.xml",
        "data/paperformat.xml",
        "views/id_card.xml",
        "views/registrant_view.xml",
    ],
    "assets": {},
    "demo": [],
    "images": [],
    "application": False,
    "installable": True,
    "auto_install": False,
    "summary": "The module issues and manages Verifiable Credentials for OpenSPP program registrants, leveraging OpenID Connect for Verifiable Presentations. It generates QR codes for secure digital sharing, integrates registrant data into VCs, and ensures credential authenticity through digital signing and encryption.",
}
