{
    "name": "OpenSPP Attendance",
    "category": "OpenSPP",
    "version": "17.0.1.3.1",
    "summary": "This module accurately tracks participant attendance for social protection program activities, capturing essential details like date, time, location, and activity type. It integrates attendance records to inform conditional benefit eligibility and leverages spp_oauth to secure API endpoints for external data submission.",
    "sequence": 1,
    "author": "OpenSPP.org",
    "website": "https://github.com/OpenSPP/openspp-modules",
    "license": "LGPL-3",
    "development_status": "Production/Stable",
    "maintainers": ["reichie020212"],
    "depends": ["base", "spp_oauth"],
    "external_dependencies": {"python": ["pytz"]},
    "data": [
        "data/ir_config_parameter_data.xml",
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/main_views.xml",
        "views/attendance_views.xml",
        "views/attendance_api_client_views.xml",
        "views/res_config_view.xml",
        "views/attendance_type_views.xml",
        "views/attendance_location_views.xml",
        "wizard/import_attendance_view.xml",
    ],
    "assets": {},
    "demo": [],
    "images": [],
    "application": True,
    "installable": True,
    "auto_install": False,
}
