{
    "name": "OpenSPP Attendance",
    "category": "OpenSPP",
    "version": "17.0.1.0.0",
    "sequence": 1,
    "author": "OpenSPP.org",
    "website": "https://github.com/OpenSPP/openspp-modules",
    "license": "LGPL-3",
    "development_status": "Production/Stable",
    "maintainers": ["reichie020212"],
    "depends": ["base", "spp_oauth"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/attendance_views.xml",
        "views/attendance_api_client_views.xml",
        "views/res_config_view.xml",
        "wizard/import_attendance_view.xml",
    ],
    "assets": {},
    "demo": [],
    "images": [],
    "application": True,
    "installable": True,
    "auto_install": False,
}
